### ISSUE TITLE
push it to the next level

### ISSUE THREAD

**Issue by dodekaeder** [afaqurk/hunts-point-pos#1]
Hey,
I'm a real noob when getting on with code, but your pos app seems to be a good start point for me.
I'm relatively new to node.js and javascript in general (but I allready earned some skills working command line based), so the list of warnings an errors that popup when I'm trying to install the app on a fresh ubuntu 14.04 with node 5.0.0 etc. are just confusing me.

I think I could do some essential work for this app while getting a bit deeper in understanding the whole
thing. For now I think the app has mostly outdated dependencies.

It would be perfect to team up for getting hunts point pos up to date.

ciao
phillip

--------------------------------------------------------------------------------------------
verbose output:

```
npm install
npm WARN engine express@4.13.3: wanted: {"node":">= 0.10.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine body-parser@1.14.1: wanted: {"node":">= 0.8"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine on-finished@2.3.0: wanted: {"node":">= 0.8"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine content-type@1.0.1: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine http-errors@1.3.1: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine raw-body@2.1.4: wanted: {"node":">= 0.8"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine iconv-lite@0.4.12: wanted: {"node":">=0.8.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine depd@1.1.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine type-is@1.6.9: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine unpipe@1.0.0: wanted: {"node":">= 0.8"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine media-typer@0.3.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine mime-types@2.1.7: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine depd@1.0.1: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine on-finished@2.3.0: wanted: {"node":">= 0.8"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine type-is@1.6.9: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine content-type@1.0.1: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine accepts@1.2.13: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine finalhandler@0.4.0: wanted: {"node":">= 0.8"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine proxy-addr@1.0.8: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine send@0.13.0: wanted: {"node":">= 0.8.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine range-parser@1.0.2: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine utils-merge@1.0.0: wanted: {"node":">= 0.4.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine fresh@0.3.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine methods@1.1.1: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine vary@1.0.1: wanted: {"node":">= 0.8"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine content-disposition@0.5.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine etag@1.7.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine cookie@0.1.3: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine serve-static@1.10.0: wanted: {"node":">= 0.8.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine mime-db@1.19.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine unpipe@1.0.0: wanted: {"node":">= 0.8"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine media-typer@0.3.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine mime-types@2.1.7: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine object-keys@1.0.1: wanted: {"node":">= 0.4"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine mime-types@2.1.7: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine negotiator@0.5.3: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine http-errors@1.3.1: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine forwarded@0.1.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine ipaddr.js@1.0.1: wanted: {"node":">= 0.2.5"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine debug@0.7.4: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine mime-db@1.19.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine base64id@0.1.0: wanted: {"node":">= 0.4.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine mime-db@1.19.0: wanted: {"node":">= 0.6"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine better-assert@1.0.2: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine debug@0.7.4: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine debug@0.7.4: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine base64-arraybuffer@0.1.2: wanted: {"node":">= 0.6.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine options@0.0.6: wanted: {"node":">=0.4.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine callsite@1.0.0: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine xmlhttprequest@1.5.0: wanted: {"node":">=0.4.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine better-assert@1.0.2: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine better-assert@1.0.2: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine better-assert@1.0.2: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine base64-arraybuffer@0.1.2: wanted: {"node":">= 0.6.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine callsite@1.0.0: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine callsite@1.0.0: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine callsite@1.0.0: wanted: {"node":"*"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
npm WARN engine options@0.0.6: wanted: {"node":">=0.4.0"} (current: {"node":"5.0.0-pre","npm":"2.14.4"})
 
> bufferutil@1.2.1 install /home/base/pos/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:64:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:155:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Linux 3.13.0-042stab092.3
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/base/pos/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v5.0.0-pre
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> utf-8-validate@1.2.1 install /home/base/pos/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:64:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:155:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Linux 3.13.0-042stab092.3
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/base/pos/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v5.0.0-pre
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install /home/base/pos/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:64:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:155:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Linux 3.13.0-042stab092.3
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/base/pos/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v5.0.0-pre
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> bufferutil@1.2.1 install /home/base/pos/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: "pre" versions of node cannot be installed, use the --nodedir flag instead
gyp ERR! stack     at install (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:64:16)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at getNodeDir (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:155:20)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Linux 3.13.0-042stab092.3
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/base/pos/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v5.0.0-pre
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
async@0.9.2 node_modules/async

body-parser@1.14.1 node_modules/body-parser
├── bytes@2.1.0
├── content-type@1.0.1
├── depd@1.1.0
├── qs@5.1.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── raw-body@2.1.4 (unpipe@1.0.0)
├── http-errors@1.3.1 (statuses@1.2.1, inherits@2.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── iconv-lite@0.4.12
└── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)

express@4.13.3 node_modules/express
├── merge-descriptors@1.0.0
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── content-type@1.0.1
├── methods@1.1.1
├── vary@1.0.1
├── range-parser@1.0.2
├── fresh@0.3.0
├── serve-static@1.10.0
├── content-disposition@0.5.0
├── etag@1.7.0
├── escape-html@1.0.2
├── array-flatten@1.1.1
├── parseurl@1.3.0
├── path-to-regexp@0.1.7
├── depd@1.0.1
├── qs@4.0.0
├── on-finished@2.3.0 (ee-first@1.1.1)
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)

nedb@1.2.1 node_modules/nedb
├── async@0.2.10
├── binary-search-tree@0.2.4
├── underscore@1.4.4
└── mkdirp@0.5.1 (minimist@0.0.8)

socket.io@1.3.7 node_modules/socket.io
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── debug@2.1.0 (ms@0.6.2)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.2.2)
├── engine.io@1.5.4 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.2, ws@0.8.0)
└── socket.io-client@1.3.7 (to-array@0.1.3, debug@0.7.4, indexof@0.0.1, object-component@0.0.3, component-bind@1.0.0, backo2@1.0.2, component-emitter@1.1.2, has-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.4)
```

**Comment by afaqurk** [comment]
I'm not sure what this issue was about but you are always welcome to submi Pull Requests or suggestions for improvement.
