### ISSUE TITLE
App cannot be started: unhandled error event

### ISSUE THREAD

**Issue by ehnydeel** [afaqurk/hunts-point-pos#4]
Hi there,

Tried to download, install and start the app. Unfortuently theres an error at the startup
saying there is an unhandled 'error' event. During the installation the bower installation
didn't work proper. There had to be an choice be selected for angular-version.

$node server/
Hunts Point POS
Server started
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventEmitter.listen (/Users/ak/Downloads/hunts-point-pos/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/ak/Downloads/hunts-point-pos/server/index.js:3:16)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by afaqurk** [comment]
> Error: listen EACCES 0.0.0.0:80

This means that you need sudo/admin priviliges on your machine to run it on port 80. You will need to start with `sudo` on linux

**Comment by afaqurk** [comment]
@ehnydeel : all taken care of? Or are you still having issues?

**Comment by ehnydeel** [comment]
ey afaqurk thanks for you help. i ran the application two times. so there was the error. issue closed. cheers
